# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDI4YzI0M2JkMGVlOTViNjVjZjE3ZThmMTg1YjVlMzU5NTljMzFjOWJhNjJmMDgxM2VlOTI1MDIyNGIyMWM3ZTRkNzg4NmI5OGIwNGM0MjhhNWQ3MDA3NjU2OTdlNDczY2MxODE5Zjc3ZGFjOWQzZjRkYzU5NDRkMGJkZWRiZjU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
